name: example_app_check
description: "A new Flutter project."

publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  firebase_app_check: ^0.2.1+14
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true