// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACQfHtN6KiDEVGl5zEh1cbyFd2Ruqr6RY',
    appId: '1:151155522161:web:1c66a623d0d434194b39d0',
    messagingSenderId: '151155522161',
    projectId: 'example-app-check-bdd04',
    authDomain: 'example-app-check-bdd04.firebaseapp.com',
    storageBucket: 'example-app-check-bdd04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0krocK9-AuwrNSkTii7uNfTgyBy7DfOQ',
    appId: '1:151155522161:android:e99f0ec773cab5bc4b39d0',
    messagingSenderId: '151155522161',
    projectId: 'example-app-check-bdd04',
    storageBucket: 'example-app-check-bdd04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqaIQXA_Ts51GPAvwqyrP9SHR0MdDvnu8',
    appId: '1:151155522161:ios:d3682ef7270b4d1d4b39d0',
    messagingSenderId: '151155522161',
    projectId: 'example-app-check-bdd04',
    storageBucket: 'example-app-check-bdd04.appspot.com',
    iosBundleId: 'com.hasankarli.exampleAppCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqaIQXA_Ts51GPAvwqyrP9SHR0MdDvnu8',
    appId: '1:151155522161:ios:13b8e578c706835c4b39d0',
    messagingSenderId: '151155522161',
    projectId: 'example-app-check-bdd04',
    storageBucket: 'example-app-check-bdd04.appspot.com',
    iosBundleId: 'com.example.exampleAppCheck.RunnerTests',
  );
}
